### ISSUE TITLE
Un-revert docs site changes that broke deployments

### ISSUE THREAD

**Issue by ptgott** [gravitational/docs#373]
On Aug 14, 2023, we merged two `gravitational/docs` PRs:

- #369
- #367

After merging, docs site deployments failed with the following message:

```
server/rehype-hljs-var.ts(165,42): error TS2345: Argument of type 'MdxJsxFlowElement \| Element' is not assignable to parameter of type 'Content'.
--
13:20:01.677 | Type 'MdxJsxFlowElement' is not assignable to type 'Content'.
13:20:01.677 | Type 'MdxJsxFlowElement' is not assignable to type 'MdxJsxFlowElementHast'.
13:20:01.677 | Types of property 'children' are incompatible.
13:20:01.677 | Type '(BlockContent \| DefinitionContent)[]' is not assignable to type 'ElementContent[]'.
13:20:01.678 | Type 'BlockContent \| DefinitionContent' is not assignable to type 'ElementContent'.
13:20:01.678 | Type 'Code' is not assignable to type 'ElementContent'.
13:20:01.678 | Type 'Code' is not assignable to type 'Raw'.
13:20:01.678 | Types of property 'type' are incompatible.
13:20:01.678 | Type '"code"' is not assignable to type '"raw"'.
13:20:01.719 | error Command failed with exit code 1.
```

This also affected the docs linter in `gravitational/teleport` CI workflows.

Let's do this:
- [ ] Investigate the cause of the error and why it evaded CI
- [ ] Find a way to prevent similar errors from slipping past CI in the future
- [ ] Un-revert the two PRs we reverted
